# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui'
#
# Created: Wed Apr 25 12:51:30 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(663, 527)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(27)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.youAreLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.youAreLabel.setFont(font)
        self.youAreLabel.setObjectName(_fromUtf8("youAreLabel"))
        self.horizontalLayout_5.addWidget(self.youAreLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tabsWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabsWidget.setObjectName(_fromUtf8("tabsWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.neighboursPeersTreeWidget = QtGui.QTreeWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neighboursPeersTreeWidget.sizePolicy().hasHeightForWidth())
        self.neighboursPeersTreeWidget.setSizePolicy(sizePolicy)
        self.neighboursPeersTreeWidget.setAlternatingRowColors(True)
        self.neighboursPeersTreeWidget.setItemsExpandable(False)
        self.neighboursPeersTreeWidget.setObjectName(_fromUtf8("neighboursPeersTreeWidget"))
        self.verticalLayout_5.addWidget(self.neighboursPeersTreeWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.peerIP = QtGui.QLineEdit(self.tab)
        self.peerIP.setText(_fromUtf8(""))
        self.peerIP.setObjectName(_fromUtf8("peerIP"))
        self.horizontalLayout_2.addWidget(self.peerIP)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.peerPort = QtGui.QLineEdit(self.tab)
        self.peerPort.setText(_fromUtf8(""))
        self.peerPort.setObjectName(_fromUtf8("peerPort"))
        self.horizontalLayout_2.addWidget(self.peerPort)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.addNeighbourPeerBtn = QtGui.QPushButton(self.tab)
        self.addNeighbourPeerBtn.setObjectName(_fromUtf8("addNeighbourPeerBtn"))
        self.horizontalLayout_2.addWidget(self.addNeighbourPeerBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.clearNeighboursBtn = QtGui.QPushButton(self.tab)
        self.clearNeighboursBtn.setObjectName(_fromUtf8("clearNeighboursBtn"))
        self.horizontalLayout_8.addWidget(self.clearNeighboursBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.tabsWidget.addTab(self.tab, _fromUtf8(""))
        self.superPeersTab = QtGui.QWidget()
        self.superPeersTab.setObjectName(_fromUtf8("superPeersTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.superPeersTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_12 = QtGui.QLabel(self.superPeersTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.superPeerLabel = QtGui.QLabel(self.superPeersTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.superPeerLabel.setFont(font)
        self.superPeerLabel.setObjectName(_fromUtf8("superPeerLabel"))
        self.horizontalLayout_7.addWidget(self.superPeerLabel)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label_9 = QtGui.QLabel(self.superPeersTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.sessionIdLabel = QtGui.QLabel(self.superPeersTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sessionIdLabel.setFont(font)
        self.sessionIdLabel.setObjectName(_fromUtf8("sessionIdLabel"))
        self.horizontalLayout.addWidget(self.sessionIdLabel)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem8 = QtGui.QSpacerItem(398, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.searchSuperPeerBtn = QtGui.QPushButton(self.superPeersTab)
        self.searchSuperPeerBtn.setMinimumSize(QtCore.QSize(0, 70))
        self.searchSuperPeerBtn.setObjectName(_fromUtf8("searchSuperPeerBtn"))
        self.horizontalLayout_6.addWidget(self.searchSuperPeerBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.superpeersTreeWidget = QtGui.QTreeWidget(self.superPeersTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.superpeersTreeWidget.sizePolicy().hasHeightForWidth())
        self.superpeersTreeWidget.setSizePolicy(sizePolicy)
        self.superpeersTreeWidget.setAlternatingRowColors(True)
        self.superpeersTreeWidget.setItemsExpandable(False)
        self.superpeersTreeWidget.setObjectName(_fromUtf8("superpeersTreeWidget"))
        self.verticalLayout_2.addWidget(self.superpeersTreeWidget)
        self.tabsWidget.addTab(self.superPeersTab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_13 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_8.addWidget(self.label_13)
        self.mypeersTreeWidget = QtGui.QTreeWidget(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mypeersTreeWidget.sizePolicy().hasHeightForWidth())
        self.mypeersTreeWidget.setSizePolicy(sizePolicy)
        self.mypeersTreeWidget.setAlternatingRowColors(True)
        self.mypeersTreeWidget.setItemsExpandable(False)
        self.mypeersTreeWidget.setObjectName(_fromUtf8("mypeersTreeWidget"))
        self.verticalLayout_8.addWidget(self.mypeersTreeWidget)
        self.tabsWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.sharedFilesListWidget = QtGui.QListWidget(self.tab_2)
        self.sharedFilesListWidget.setAlternatingRowColors(True)
        self.sharedFilesListWidget.setObjectName(_fromUtf8("sharedFilesListWidget"))
        self.verticalLayout_4.addWidget(self.sharedFilesListWidget)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.reloadSharedFilesBtn = QtGui.QPushButton(self.tab_2)
        self.reloadSharedFilesBtn.setObjectName(_fromUtf8("reloadSharedFilesBtn"))
        self.horizontalLayout_9.addWidget(self.reloadSharedFilesBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tabsWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.downloadsTreeWidget = QtGui.QTreeWidget(self.tab_3)
        self.downloadsTreeWidget.setAlternatingRowColors(True)
        self.downloadsTreeWidget.setObjectName(_fromUtf8("downloadsTreeWidget"))
        self.verticalLayout_3.addWidget(self.downloadsTreeWidget)
        self.label_8 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.uploadsTreeWidget = QtGui.QTreeWidget(self.tab_3)
        self.uploadsTreeWidget.setAlternatingRowColors(True)
        self.uploadsTreeWidget.setObjectName(_fromUtf8("uploadsTreeWidget"))
        self.verticalLayout_3.addWidget(self.uploadsTreeWidget)
        self.tabsWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.searchLineEdit = QtGui.QLineEdit(self.tab_4)
        self.searchLineEdit.setObjectName(_fromUtf8("searchLineEdit"))
        self.horizontalLayout_3.addWidget(self.searchLineEdit)
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.ttlFilesSearchSpinBox = QtGui.QSpinBox(self.tab_4)
        self.ttlFilesSearchSpinBox.setMinimum(1)
        self.ttlFilesSearchSpinBox.setProperty("value", 3)
        self.ttlFilesSearchSpinBox.setObjectName(_fromUtf8("ttlFilesSearchSpinBox"))
        self.horizontalLayout_3.addWidget(self.ttlFilesSearchSpinBox)
        self.searchBtn = QtGui.QPushButton(self.tab_4)
        self.searchBtn.setObjectName(_fromUtf8("searchBtn"))
        self.horizontalLayout_3.addWidget(self.searchBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.resultsTreeWidget = QtGui.QTreeWidget(self.tab_4)
        self.resultsTreeWidget.setAlternatingRowColors(True)
        self.resultsTreeWidget.setObjectName(_fromUtf8("resultsTreeWidget"))
        self.verticalLayout_6.addWidget(self.resultsTreeWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem10 = QtGui.QSpacerItem(358, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.tabsWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.loggingTextBrowser = QtGui.QTextBrowser(self.tab_5)
        self.loggingTextBrowser.setObjectName(_fromUtf8("loggingTextBrowser"))
        self.verticalLayout_7.addWidget(self.loggingTextBrowser)
        self.tabsWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabsWidget)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabsWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Kazaa client", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "by Ferrari Luca, Bersani Marco, Lodi Giovanni", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "You are a:", None, QtGui.QApplication.UnicodeUTF8))
        self.youAreLabel.setText(QtGui.QApplication.translate("MainWindow", "peer", None, QtGui.QApplication.UnicodeUTF8))
        self.neighboursPeersTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Peer IP", None, QtGui.QApplication.UnicodeUTF8))
        self.neighboursPeersTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Peer Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Peer IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Peer port", None, QtGui.QApplication.UnicodeUTF8))
        self.addNeighbourPeerBtn.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.clearNeighboursBtn.setText(QtGui.QApplication.translate("MainWindow", "Clear all neighbours", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Neighbours", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Your superpeer:", None, QtGui.QApplication.UnicodeUTF8))
        self.superPeerLabel.setText(QtGui.QApplication.translate("MainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Your sessionid:", None, QtGui.QApplication.UnicodeUTF8))
        self.sessionIdLabel.setText(QtGui.QApplication.translate("MainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.searchSuperPeerBtn.setText(QtGui.QApplication.translate("MainWindow", "Search a super peer!", None, QtGui.QApplication.UnicodeUTF8))
        self.superpeersTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "SuperPeer IP", None, QtGui.QApplication.UnicodeUTF8))
        self.superpeersTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "SuperPeer Port", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.superPeersTab), QtGui.QApplication.translate("MainWindow", "Superpeers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Your connected peers:", None, QtGui.QApplication.UnicodeUTF8))
        self.mypeersTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Peer IP", None, QtGui.QApplication.UnicodeUTF8))
        self.mypeersTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Peer Port", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "My peers", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadSharedFilesBtn.setText(QtGui.QApplication.translate("MainWindow", "Reload shared files from HD", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Shared files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Downloads:", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Percentage", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadsTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Peer", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadsTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Md5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Uploads:", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Percentage", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadsTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Peer", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadsTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Md5", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Transfers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "File name to search:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "TTL:", None, QtGui.QApplication.UnicodeUTF8))
        self.searchBtn.setText(QtGui.QApplication.translate("MainWindow", "Search!", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Peer IP", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Peer port", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Md5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Double click on a file to download it", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Logging", None, QtGui.QApplication.UnicodeUTF8))

