# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon May 28 18:13:16 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(663, 527)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(27)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabsWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabsWidget.setObjectName(_fromUtf8("tabsWidget"))
        self.superPeersTab = QtGui.QWidget()
        self.superPeersTab.setObjectName(_fromUtf8("superPeersTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.superPeersTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.loginGroupBox = QtGui.QGroupBox(self.superPeersTab)
        self.loginGroupBox.setObjectName(_fromUtf8("loginGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.loginGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.loginGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.trackerIpLineEdit = QtGui.QLineEdit(self.loginGroupBox)
        self.trackerIpLineEdit.setObjectName(_fromUtf8("trackerIpLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.trackerIpLineEdit)
        self.label_6 = QtGui.QLabel(self.loginGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.trackerPortLineEdit = QtGui.QLineEdit(self.loginGroupBox)
        self.trackerPortLineEdit.setObjectName(_fromUtf8("trackerPortLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.trackerPortLineEdit)
        self.horizontalLayout_5.addLayout(self.formLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.loginBtn = QtGui.QPushButton(self.loginGroupBox)
        self.loginBtn.setMinimumSize(QtCore.QSize(0, 70))
        self.loginBtn.setObjectName(_fromUtf8("loginBtn"))
        self.horizontalLayout_5.addWidget(self.loginBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.loginGroupBox)
        self.logoutGroupBox = QtGui.QGroupBox(self.superPeersTab)
        self.logoutGroupBox.setObjectName(_fromUtf8("logoutGroupBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.logoutGroupBox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_9 = QtGui.QLabel(self.logoutGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.sessionIdLabel = QtGui.QLabel(self.logoutGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sessionIdLabel.setFont(font)
        self.sessionIdLabel.setObjectName(_fromUtf8("sessionIdLabel"))
        self.horizontalLayout_2.addWidget(self.sessionIdLabel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem4 = QtGui.QSpacerItem(328, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.logoutBtn = QtGui.QPushButton(self.logoutGroupBox)
        self.logoutBtn.setEnabled(True)
        self.logoutBtn.setMinimumSize(QtCore.QSize(0, 70))
        self.logoutBtn.setObjectName(_fromUtf8("logoutBtn"))
        self.horizontalLayout.addWidget(self.logoutBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.logoutGroupBox)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.trackerStatusLabel = QtGui.QLabel(self.superPeersTab)
        self.trackerStatusLabel.setObjectName(_fromUtf8("trackerStatusLabel"))
        self.verticalLayout_5.addWidget(self.trackerStatusLabel)
        self.tabsWidget.addTab(self.superPeersTab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.sharedFilesListWidget = QtGui.QListWidget(self.tab_2)
        self.sharedFilesListWidget.setAlternatingRowColors(True)
        self.sharedFilesListWidget.setObjectName(_fromUtf8("sharedFilesListWidget"))
        self.verticalLayout_4.addWidget(self.sharedFilesListWidget)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.reloadSharedFilesBtn = QtGui.QPushButton(self.tab_2)
        self.reloadSharedFilesBtn.setObjectName(_fromUtf8("reloadSharedFilesBtn"))
        self.horizontalLayout_9.addWidget(self.reloadSharedFilesBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tabsWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.downloadsTreeWidget = QtGui.QTreeWidget(self.tab_3)
        self.downloadsTreeWidget.setAlternatingRowColors(True)
        self.downloadsTreeWidget.setObjectName(_fromUtf8("downloadsTreeWidget"))
        self.verticalLayout_3.addWidget(self.downloadsTreeWidget)
        self.label_8 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.uploadsTreeWidget = QtGui.QTreeWidget(self.tab_3)
        self.uploadsTreeWidget.setAlternatingRowColors(True)
        self.uploadsTreeWidget.setObjectName(_fromUtf8("uploadsTreeWidget"))
        self.verticalLayout_3.addWidget(self.uploadsTreeWidget)
        self.tabsWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.searchLineEdit = QtGui.QLineEdit(self.tab_4)
        self.searchLineEdit.setObjectName(_fromUtf8("searchLineEdit"))
        self.horizontalLayout_3.addWidget(self.searchLineEdit)
        self.searchBtn = QtGui.QPushButton(self.tab_4)
        self.searchBtn.setObjectName(_fromUtf8("searchBtn"))
        self.horizontalLayout_3.addWidget(self.searchBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.resultsTreeWidget = QtGui.QTreeWidget(self.tab_4)
        self.resultsTreeWidget.setAlternatingRowColors(True)
        self.resultsTreeWidget.setObjectName(_fromUtf8("resultsTreeWidget"))
        self.verticalLayout_6.addWidget(self.resultsTreeWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem7 = QtGui.QSpacerItem(358, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.tabsWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.loggingTextBrowser = QtGui.QTextBrowser(self.tab_5)
        self.loggingTextBrowser.setObjectName(_fromUtf8("loggingTextBrowser"))
        self.verticalLayout_7.addWidget(self.loggingTextBrowser)
        self.tabsWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabsWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabsWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Bittorrent client", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "by Ferrari Luca, Bersani Marco, Lodi Giovanni", None, QtGui.QApplication.UnicodeUTF8))
        self.loginGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Choose your tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.loginBtn.setText(QtGui.QApplication.translate("MainWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.logoutGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Tracker status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Your sessionid:", None, QtGui.QApplication.UnicodeUTF8))
        self.sessionIdLabel.setText(QtGui.QApplication.translate("MainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.logoutBtn.setText(QtGui.QApplication.translate("MainWindow", "Logout", None, QtGui.QApplication.UnicodeUTF8))
        self.trackerStatusLabel.setText(QtGui.QApplication.translate("MainWindow", "Disconnesso", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.superPeersTab), QtGui.QApplication.translate("MainWindow", "Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadSharedFilesBtn.setText(QtGui.QApplication.translate("MainWindow", "Reload shared files from HD", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Shared files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Downloads:", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadsTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Part num", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadsTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Percentage", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadsTreeWidget.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Peer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Uploads:", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadsTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Part num", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadsTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Percentage", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadsTreeWidget.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Peer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Transfers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "File name to search:", None, QtGui.QApplication.UnicodeUTF8))
        self.searchBtn.setText(QtGui.QApplication.translate("MainWindow", "Search!", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "File size", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Part size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Double click on a file to download it", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Logging", None, QtGui.QApplication.UnicodeUTF8))

