__author__ = 'maurizio'
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Node_GUIka.ui'
#
# Created: Thu Apr 26 22:34:18 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NodeWindow(object):
    def setupUi(self, NodeWindow):
        NodeWindow.setObjectName(_fromUtf8("NodeWindow"))
        NodeWindow.resize(683, 626)
        NodeWindow.setWindowTitle(QtGui.QApplication.translate("NodeWindow", "FGMteamCreation", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(NodeWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 80, 581, 301))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Find_Supernode_TAB = QtGui.QWidget()
        self.Find_Supernode_TAB.setObjectName(_fromUtf8("Find_Supernode_TAB"))
        self.Node_Neigh_tree = QtGui.QTreeWidget(self.Find_Supernode_TAB)
        self.Node_Neigh_tree.setGeometry(QtCore.QRect(10, 90, 551, 81))
        self.Node_Neigh_tree.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Node_Neigh_tree.setObjectName(_fromUtf8("Node_Neigh_tree"))
        self.Node_Neigh_tree.headerItem().setText(0, QtGui.QApplication.translate("NodeWindow", "SUPERnode IP", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_Neigh_tree.headerItem().setText(1, QtGui.QApplication.translate("NodeWindow", "SUPERnode Port ", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_Root_Port = QtGui.QLineEdit(self.Find_Supernode_TAB)
        self.Node_Root_Port.setGeometry(QtCore.QRect(400, 20, 51, 22))
        self.Node_Root_Port.setObjectName(_fromUtf8("Node_Root_Port"))
        self.label_5 = QtGui.QLabel(self.Find_Supernode_TAB)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 111, 22))
        self.label_5.setText(QtGui.QApplication.translate("NodeWindow", "SUPERnode    ->", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.Find_Supernode_TAB)
        self.label_6.setGeometry(QtCore.QRect(120, 20, 16, 22))
        self.label_6.setText(QtGui.QApplication.translate("NodeWindow", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.Find_Supernode_TAB)
        self.label_7.setGeometry(QtCore.QRect(360, 20, 41, 22))
        self.label_7.setText(QtGui.QApplication.translate("NodeWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Node_Root_IP = QtGui.QLineEdit(self.Find_Supernode_TAB)
        self.Node_Root_IP.setGeometry(QtCore.QRect(140, 20, 201, 22))
        self.Node_Root_IP.setObjectName(_fromUtf8("Node_Root_IP"))
        self.Node_START_Btn = QtGui.QPushButton(self.Find_Supernode_TAB)
        self.Node_START_Btn.setGeometry(QtCore.QRect(462, 17, 97, 27))
        self.Node_START_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Node_START_Btn.setText(QtGui.QApplication.translate("NodeWindow", "START!", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_START_Btn.setAutoDefault(False)
        self.Node_START_Btn.setDefault(True)
        self.Node_START_Btn.setObjectName(_fromUtf8("Node_START_Btn"))
        self.line_2 = QtGui.QFrame(self.Find_Supernode_TAB)
        self.line_2.setGeometry(QtCore.QRect(3, 50, 571, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.Find_Supernode_TAB)
        self.line_3.setGeometry(QtCore.QRect(3, 187, 571, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label = QtGui.QLabel(self.Find_Supernode_TAB)
        self.label.setGeometry(QtCore.QRect(98, 200, 401, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText(QtGui.QApplication.translate("NodeWindow", "Actually, you are connected with SUPERnode that has:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.Find_Supernode_TAB)
        self.label_2.setGeometry(QtCore.QRect(120, 230, 21, 17))
        self.label_2.setText(QtGui.QApplication.translate("NodeWindow", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.Find_Supernode_TAB)
        self.label_3.setGeometry(QtCore.QRect(320, 230, 41, 17))
        self.label_3.setText(QtGui.QApplication.translate("NodeWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.Find_Supernode_TAB)
        self.label_4.setGeometry(QtCore.QRect(270, 64, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setText(QtGui.QApplication.translate("NodeWindow", "Find new SUPERnodes in the network.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.Node_ChangeSuperNode_Btn = QtGui.QPushButton(self.Find_Supernode_TAB)
        self.Node_ChangeSuperNode_Btn.setGeometry(QtCore.QRect(110, 60, 151, 27))
        self.Node_ChangeSuperNode_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Node_ChangeSuperNode_Btn.setText(QtGui.QApplication.translate("NodeWindow", "Change SUPERnode", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_ChangeSuperNode_Btn.setDefault(True)
        self.Node_ChangeSuperNode_Btn.setFlat(False)
        self.Node_ChangeSuperNode_Btn.setObjectName(_fromUtf8("Node_ChangeSuperNode_Btn"))
        self.label_8 = QtGui.QLabel(self.Find_Supernode_TAB)
        self.label_8.setGeometry(QtCore.QRect(150, 170, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_8.setText(QtGui.QApplication.translate("NodeWindow", "To select one, double-click on the item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.Node_TTL_FindNeigh = QtGui.QLineEdit(self.Find_Supernode_TAB)
        self.Node_TTL_FindNeigh.setGeometry(QtCore.QRect(50, 62, 51, 22))
        self.Node_TTL_FindNeigh.setObjectName(_fromUtf8("Node_TTL_FindNeigh"))
        self.label_9 = QtGui.QLabel(self.Find_Supernode_TAB)
        self.label_9.setGeometry(QtCore.QRect(15, 63, 31, 22))
        self.label_9.setText(QtGui.QApplication.translate("NodeWindow", "TTL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.Node_ActualSuperNode_IP_text = QtGui.QLabel(self.Find_Supernode_TAB)
        self.Node_ActualSuperNode_IP_text.setGeometry(QtCore.QRect(160, 227, 111, 22))
        self.Node_ActualSuperNode_IP_text.setText(QtGui.QApplication.translate("NodeWindow", "no connection", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_ActualSuperNode_IP_text.setObjectName(_fromUtf8("Node_ActualSuperNode_IP_text"))
        self.Node_ActualSuperNode_Port_text = QtGui.QLabel(self.Find_Supernode_TAB)
        self.Node_ActualSuperNode_Port_text.setGeometry(QtCore.QRect(360, 228, 111, 22))
        self.Node_ActualSuperNode_Port_text.setText(QtGui.QApplication.translate("NodeWindow", "no connection", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_ActualSuperNode_Port_text.setObjectName(_fromUtf8("Node_ActualSuperNode_Port_text"))
        self.tabWidget.addTab(self.Find_Supernode_TAB, _fromUtf8(""))
        self.Addfile_TAB = QtGui.QWidget()
        self.Addfile_TAB.setObjectName(_fromUtf8("Addfile_TAB"))
        self.Node_Files_Path = QtGui.QLineEdit(self.Addfile_TAB)
        self.Node_Files_Path.setGeometry(QtCore.QRect(15, 40, 451, 31))
        self.Node_Files_Path.setObjectName(_fromUtf8("Node_Files_Path"))
        self.Node_Search_in_Path_Btn = QtGui.QPushButton(self.Addfile_TAB)
        self.Node_Search_in_Path_Btn.setGeometry(QtCore.QRect(465, 40, 97, 31))
        self.Node_Search_in_Path_Btn.setText(QtGui.QApplication.translate("NodeWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_Search_in_Path_Btn.setObjectName(_fromUtf8("Node_Search_in_Path_Btn"))
        self.Lookforfiles_label = QtGui.QLabel(self.Addfile_TAB)
        self.Lookforfiles_label.setGeometry(QtCore.QRect(80, 10, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lookforfiles_label.setFont(font)
        self.Lookforfiles_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Lookforfiles_label.setText(QtGui.QApplication.translate("NodeWindow", "Look for the files to add in the specified path", None, QtGui.QApplication.UnicodeUTF8))
        self.Lookforfiles_label.setObjectName(_fromUtf8("Lookforfiles_label"))
        self.label_10 = QtGui.QLabel(self.Addfile_TAB)
        self.label_10.setGeometry(QtCore.QRect(170, 247, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_10.setText(QtGui.QApplication.translate("NodeWindow", "To select one, double-click on the item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.line = QtGui.QFrame(self.Addfile_TAB)
        self.line.setGeometry(QtCore.QRect(3, 72, 571, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.Node_listView = QtGui.QListView(self.Addfile_TAB)
        self.Node_listView.setGeometry(QtCore.QRect(13, 92, 551, 151))
        self.Node_listView.setObjectName(_fromUtf8("Node_listView"))
        self.tabWidget.addTab(self.Addfile_TAB, _fromUtf8(""))
        self.Removefiles_TAB = QtGui.QWidget()
        self.Removefiles_TAB.setObjectName(_fromUtf8("Removefiles_TAB"))
        self.label_11 = QtGui.QLabel(self.Removefiles_TAB)
        self.label_11.setGeometry(QtCore.QRect(161, 239, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_11.setText(QtGui.QApplication.translate("NodeWindow", "To remove one, double-click on the item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.Node_AddedFile_List = QtGui.QListWidget(self.Removefiles_TAB)
        self.Node_AddedFile_List.setGeometry(QtCore.QRect(13, 40, 551, 192))
        self.Node_AddedFile_List.setObjectName(_fromUtf8("Node_AddedFile_List"))
        self.Lookforfiles_label_2 = QtGui.QLabel(self.Removefiles_TAB)
        self.Lookforfiles_label_2.setGeometry(QtCore.QRect(118, 10, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lookforfiles_label_2.setFont(font)
        self.Lookforfiles_label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Lookforfiles_label_2.setText(QtGui.QApplication.translate("NodeWindow", "Files present on SUPERnode Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.Lookforfiles_label_2.setObjectName(_fromUtf8("Lookforfiles_label_2"))
        self.tabWidget.addTab(self.Removefiles_TAB, _fromUtf8(""))
        self.Searchfile_TAB = QtGui.QWidget()
        self.Searchfile_TAB.setObjectName(_fromUtf8("Searchfile_TAB"))
        self.Node_Search_string_Btn = QtGui.QPushButton(self.Searchfile_TAB)
        self.Node_Search_string_Btn.setGeometry(QtCore.QRect(464, 12, 97, 31))
        self.Node_Search_string_Btn.setText(QtGui.QApplication.translate("NodeWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_Search_string_Btn.setObjectName(_fromUtf8("Node_Search_string_Btn"))
        self.Node_SearchString = QtGui.QLineEdit(self.Searchfile_TAB)
        self.Node_SearchString.setGeometry(QtCore.QRect(14, 12, 451, 31))
        self.Node_SearchString.setObjectName(_fromUtf8("Node_SearchString"))
        self.Node_tree_of_file_found = QtGui.QTreeWidget(self.Searchfile_TAB)
        self.Node_tree_of_file_found.setGeometry(QtCore.QRect(10, 50, 551, 192))
        self.Node_tree_of_file_found.setObjectName(_fromUtf8("Node_tree_of_file_found"))
        self.Node_tree_of_file_found.headerItem().setText(0, QtGui.QApplication.translate("NodeWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_tree_of_file_found.headerItem().setText(1, QtGui.QApplication.translate("NodeWindow", "File name", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_tree_of_file_found.headerItem().setText(2, QtGui.QApplication.translate("NodeWindow", "peer\'s IP", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_tree_of_file_found.headerItem().setText(3, QtGui.QApplication.translate("NodeWindow", "peer\'s Port", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_tree_of_file_found.headerItem().setText(4, QtGui.QApplication.translate("NodeWindow", "md5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12 = QtGui.QLabel(self.Searchfile_TAB)
        self.label_12.setGeometry(QtCore.QRect(170, 244, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_12.setText(QtGui.QApplication.translate("NodeWindow", "To download one, double-click on the item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tabWidget.addTab(self.Searchfile_TAB, _fromUtf8(""))
        self.Logout_TAB = QtGui.QWidget()
        self.Logout_TAB.setObjectName(_fromUtf8("Logout_TAB"))
        self.Node_Logout_Btn = QtGui.QPushButton(self.Logout_TAB)
        self.Node_Logout_Btn.setGeometry(QtCore.QRect(10, 10, 561, 251))
        self.Node_Logout_Btn.setText(QtGui.QApplication.translate("NodeWindow", "Logout", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_Logout_Btn.setObjectName(_fromUtf8("Node_Logout_Btn"))
        self.tabWidget.addTab(self.Logout_TAB, _fromUtf8(""))
        self.NodeTitleLabel = QtGui.QLabel(self.centralwidget)
        self.NodeTitleLabel.setGeometry(QtCore.QRect(120, 20, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.NodeTitleLabel.setFont(font)
        self.NodeTitleLabel.setText(QtGui.QApplication.translate("NodeWindow", "NODE (PEER) SECTION", None, QtGui.QApplication.UnicodeUTF8))
        self.NodeTitleLabel.setObjectName(_fromUtf8("NodeTitleLabel"))
        self.LogBox_text = QtGui.QTextBrowser(self.centralwidget)
        self.LogBox_text.setGeometry(QtCore.QRect(50, 410, 581, 141))
        self.LogBox_text.setObjectName(_fromUtf8("LogBox_text"))
        self.LogBox_Label = QtGui.QLabel(self.centralwidget)
        self.LogBox_Label.setGeometry(QtCore.QRect(310, 390, 61, 17))
        self.LogBox_Label.setText(QtGui.QApplication.translate("NodeWindow", "Log Box", None, QtGui.QApplication.UnicodeUTF8))
        self.LogBox_Label.setObjectName(_fromUtf8("LogBox_Label"))
        NodeWindow.setCentralWidget(self.centralwidget)
        self.Node_statusbar = QtGui.QStatusBar(NodeWindow)
        self.Node_statusbar.setObjectName(_fromUtf8("Node_statusbar"))
        NodeWindow.setStatusBar(self.Node_statusbar)

        self.retranslateUi(NodeWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NodeWindow)

    def retranslateUi(self, NodeWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Find_Supernode_TAB), QtGui.QApplication.translate("NodeWindow", "Find SUPERnodes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Addfile_TAB), QtGui.QApplication.translate("NodeWindow", "Add Files", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Removefiles_TAB), QtGui.QApplication.translate("NodeWindow", "Remove Files", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Searchfile_TAB), QtGui.QApplication.translate("NodeWindow", "Search Files", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Logout_TAB), QtGui.QApplication.translate("NodeWindow", "Logout", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    NodeWindow = QtGui.QMainWindow()
    ui = Ui_NodeWindow()
    ui.setupUi(NodeWindow)
    NodeWindow.show()
    sys.exit(app.exec_())
