__author__ = 'maurizio'

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuperNode_GUIka.ui'
#
# Created: Thu Apr 26 21:00:34 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SuperNode(object):
    def setupUi(self, SuperNode):
        SuperNode.setObjectName(_fromUtf8("SuperNode"))
        SuperNode.resize(623, 452)
        SuperNode.setWindowTitle(QtGui.QApplication.translate("SuperNode", "FGMteamCreation - SuperNode_GUIka", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(SuperNode)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.SuperNodeTitleLabel = QtGui.QLabel(self.centralwidget)
        self.SuperNodeTitleLabel.setGeometry(QtCore.QRect(20, 10, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.SuperNodeTitleLabel.setFont(font)
        self.SuperNodeTitleLabel.setText(QtGui.QApplication.translate("SuperNode", "SUPERNODE (DIRECTORY) SECTION", None, QtGui.QApplication.UnicodeUTF8))
        self.SuperNodeTitleLabel.setObjectName(_fromUtf8("SuperNodeTitleLabel"))
        self.LogBox_Label = QtGui.QLabel(self.centralwidget)
        self.LogBox_Label.setGeometry(QtCore.QRect(280, 219, 61, 17))
        self.LogBox_Label.setText(QtGui.QApplication.translate("SuperNode", "Log Box", None, QtGui.QApplication.UnicodeUTF8))
        self.LogBox_Label.setObjectName(_fromUtf8("LogBox_Label"))
        self.SuperNode_LogBox_text = QtGui.QTextBrowser(self.centralwidget)
        self.SuperNode_LogBox_text.setGeometry(QtCore.QRect(20, 242, 581, 181))
        self.SuperNode_LogBox_text.setObjectName(_fromUtf8("SuperNode_LogBox_text"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 601, 161))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.roots = QtGui.QWidget()
        self.roots.setObjectName(_fromUtf8("roots"))
        self.SuperNode_EXIT_Btn = QtGui.QPushButton(self.roots)
        self.SuperNode_EXIT_Btn.setGeometry(QtCore.QRect(440, 74, 151, 27))
        self.SuperNode_EXIT_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SuperNode_EXIT_Btn.setText(QtGui.QApplication.translate("SuperNode", "EXIT", None, QtGui.QApplication.UnicodeUTF8))
        self.SuperNode_EXIT_Btn.setAutoDefault(False)
        self.SuperNode_EXIT_Btn.setDefault(False)
        self.SuperNode_EXIT_Btn.setObjectName(_fromUtf8("SuperNode_EXIT_Btn"))
        self.SuperNode_Root_IP_1 = QtGui.QLineEdit(self.roots)
        self.SuperNode_Root_IP_1.setGeometry(QtCore.QRect(109, 29, 201, 22))
        self.SuperNode_Root_IP_1.setObjectName(_fromUtf8("SuperNode_Root_IP_1"))
        self.SuperNode_Root_IP_2 = QtGui.QLineEdit(self.roots)
        self.SuperNode_Root_IP_2.setGeometry(QtCore.QRect(109, 76, 201, 22))
        self.SuperNode_Root_IP_2.setObjectName(_fromUtf8("SuperNode_Root_IP_2"))
        self.label_5 = QtGui.QLabel(self.roots)
        self.label_5.setGeometry(QtCore.QRect(9, 29, 81, 22))
        self.label_5.setText(QtGui.QApplication.translate("SuperNode", "ROOT 1    ->", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_7 = QtGui.QLabel(self.roots)
        self.label_7.setGeometry(QtCore.QRect(329, 29, 41, 22))
        self.label_7.setText(QtGui.QApplication.translate("SuperNode", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.roots)
        self.label_8.setGeometry(QtCore.QRect(9, 76, 81, 22))
        self.label_8.setText(QtGui.QApplication.translate("SuperNode", "ROOT 2    ->", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.SuperNode_Root_Port_2 = QtGui.QLineEdit(self.roots)
        self.SuperNode_Root_Port_2.setGeometry(QtCore.QRect(369, 76, 51, 22))
        self.SuperNode_Root_Port_2.setObjectName(_fromUtf8("SuperNode_Root_Port_2"))
        self.SuperNode_Root_Port = QtGui.QLineEdit(self.roots)
        self.SuperNode_Root_Port.setGeometry(QtCore.QRect(369, 29, 51, 22))
        self.SuperNode_Root_Port.setObjectName(_fromUtf8("SuperNode_Root_Port"))
        self.label_10 = QtGui.QLabel(self.roots)
        self.label_10.setGeometry(QtCore.QRect(89, 76, 16, 22))
        self.label_10.setText(QtGui.QApplication.translate("SuperNode", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_9 = QtGui.QLabel(self.roots)
        self.label_9.setGeometry(QtCore.QRect(329, 76, 41, 22))
        self.label_9.setText(QtGui.QApplication.translate("SuperNode", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_6 = QtGui.QLabel(self.roots)
        self.label_6.setGeometry(QtCore.QRect(89, 29, 16, 22))
        self.label_6.setText(QtGui.QApplication.translate("SuperNode", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.SuperNode_START_Btn = QtGui.QPushButton(self.roots)
        self.SuperNode_START_Btn.setGeometry(QtCore.QRect(440, 26, 151, 27))
        self.SuperNode_START_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SuperNode_START_Btn.setText(QtGui.QApplication.translate("SuperNode", "START!", None, QtGui.QApplication.UnicodeUTF8))
        self.SuperNode_START_Btn.setAutoDefault(False)
        self.SuperNode_START_Btn.setDefault(True)
        self.SuperNode_START_Btn.setObjectName(_fromUtf8("SuperNode_START_Btn"))
        self.tabWidget.addTab(self.roots, _fromUtf8(""))
        self.SuperNode_find_Supernode = QtGui.QWidget()
        self.SuperNode_find_Supernode.setObjectName(_fromUtf8("SuperNode_find_Supernode"))
        self.label_11 = QtGui.QLabel(self.SuperNode_find_Supernode)
        self.label_11.setGeometry(QtCore.QRect(15, 48, 31, 22))
        self.label_11.setText(QtGui.QApplication.translate("SuperNode", "TTL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.ChangeSuperNode_Btn = QtGui.QPushButton(self.SuperNode_find_Supernode)
        self.ChangeSuperNode_Btn.setGeometry(QtCore.QRect(110, 46, 151, 27))
        self.ChangeSuperNode_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ChangeSuperNode_Btn.setText(QtGui.QApplication.translate("SuperNode", "Change SUPERnode", None, QtGui.QApplication.UnicodeUTF8))
        self.ChangeSuperNode_Btn.setDefault(True)
        self.ChangeSuperNode_Btn.setFlat(False)
        self.ChangeSuperNode_Btn.setObjectName(_fromUtf8("ChangeSuperNode_Btn"))
        self.SuperNode_TTL_FindNeigh = QtGui.QLineEdit(self.SuperNode_find_Supernode)
        self.SuperNode_TTL_FindNeigh.setGeometry(QtCore.QRect(50, 48, 51, 22))
        self.SuperNode_TTL_FindNeigh.setObjectName(_fromUtf8("SuperNode_TTL_FindNeigh"))
        self.label_4 = QtGui.QLabel(self.SuperNode_find_Supernode)
        self.label_4.setGeometry(QtCore.QRect(270, 50, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setText(QtGui.QApplication.translate("SuperNode", "Find others SUPERnodes in the network.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.SuperNode_find_Supernode, _fromUtf8(""))
        self.actually_supernode = QtGui.QWidget()
        self.actually_supernode.setObjectName(_fromUtf8("actually_supernode"))
        self.SuperNode_Neighbours_list = QtGui.QTreeWidget(self.actually_supernode)
        self.SuperNode_Neighbours_list.setGeometry(QtCore.QRect(8, 8, 581, 111))
        self.SuperNode_Neighbours_list.setObjectName(_fromUtf8("SuperNode_Neighbours_list"))
        self.SuperNode_Neighbours_list.headerItem().setText(0, QtGui.QApplication.translate("SuperNode", "Neighbour\'s IP", None, QtGui.QApplication.UnicodeUTF8))
        self.SuperNode_Neighbours_list.headerItem().setText(1, QtGui.QApplication.translate("SuperNode", "Neighbour\'s Port", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.addTab(self.actually_supernode, _fromUtf8(""))
        SuperNode.setCentralWidget(self.centralwidget)
        self.SuperNode_statusbar = QtGui.QStatusBar(SuperNode)
        self.SuperNode_statusbar.setObjectName(_fromUtf8("SuperNode_statusbar"))
        SuperNode.setStatusBar(self.SuperNode_statusbar)

        self.retranslateUi(SuperNode)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(SuperNode)

    def retranslateUi(self, SuperNode):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.roots), QtGui.QApplication.translate("SuperNode", "Specify Roots", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SuperNode_find_Supernode), QtGui.QApplication.translate("SuperNode", "Find Supernode", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actually_supernode), QtGui.QApplication.translate("SuperNode", "Actually Neighbours", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SuperNode = QtGui.QMainWindow()
    ui = Ui_SuperNode()
    ui.setupUi(SuperNode)
    SuperNode.show()
    sys.exit(app.exec_())
